<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE familie [
<!ELEMENT familie (generation)>
<!ELEMENT generation (Frau | Mann | generation)*>
<!ELEMENT Mann EMPTY>
<!ATTLIST  Mann 
    vorname CDATA #REQUIRED
    nachname CDATA #REQUIRED
    geburtsdatum CDATA #REQUIRED
    geburtsort CDATA #REQUIRED
    todesdatum CDATA #IMPLIED
    ehepartner CDATA #IMPLIED
    mutter CDATA #IMPLIED
    vater CDATA #IMPLIED
    id CDATA #REQUIRED
    familyId CDATA #IMPLIED
>
<!ELEMENT Frau EMPTY>
<!ATTLIST  Frau 
    vorname CDATA #REQUIRED
    nachname CDATA #REQUIRED
    geburtsdatum CDATA #REQUIRED
    geburtsort CDATA #REQUIRED
    todesdatum CDATA #IMPLIED
    ehepartner CDATA #IMPLIED
    mutter CDATA #IMPLIED
    vater CDATA #IMPLIED
    id CDATA #REQUIRED
    familyId CDATA #IMPLIED
>
]>
<familie>
    <generation>
        <Frau vorname="Alexandra" nachname="Ewing" geburtsdatum="15-01-36" geburtsort="Laken" todesdatum="" ehepartner="" mutter="16" vater="15" id="54" familyId=""/>
        <Mann vorname="Brenden" nachname="Ewing" geburtsdatum="01-06-46" geburtsort="Enna" todesdatum="" ehepartner="" mutter="16" vater="15" id="78" familyId=""/>
        <generation>
            <Frau vorname="Jasmine" nachname="Lee" geburtsdatum="11-08-48" geburtsort="Bearberry" todesdatum="" ehepartner="" mutter="5" vater="6" id="13" familyId=""/>
            <Mann vorname="Finn" nachname="Lee" geburtsdatum="29-12-16" geburtsort="Lacombe County" todesdatum="" ehepartner="" mutter="5" vater="6" id="14" familyId=""/>
            <Mann vorname="Arthur" nachname="Ewing" geburtsdatum="19-07-58" geburtsort="Pereira" todesdatum="" ehepartner="16" mutter="" vater="" id="15" familyId=""/>
            <Frau vorname="Kylee" nachname="Lee" geburtsdatum="15-12-98" geburtsort="Acireale" todesdatum="" ehepartner="15" mutter="5" vater="6" id="16" familyId=""/>


            <Frau vorname="Stacy" nachname="Lee" geburtsdatum="26-09-41" geburtsort="Colobraro" todesdatum="" ehepartner="" mutter="7" vater="8" id="17" familyId=""/>
            <Frau vorname="Hilda" nachname="Lee" geburtsdatum="28-07-16" geburtsort="Lavoir" todesdatum="" ehepartner="" mutter="7" vater="8" id="18" familyId=""/>
            <Mann vorname="Amos" nachname="Lee" geburtsdatum="06-03-44" geburtsort="Ninhue" todesdatum="" ehepartner="20" mutter="7" vater="8" id="19" familyId=""/>
            <Frau vorname="Halla" nachname="Watkins" geburtsdatum="21-12-17" geburtsort="Lille" todesdatum="" ehepartner="19" mutter="" vater="" id="20" familyId=""/>


            <Mann vorname="Bert" nachname="Casey" geburtsdatum="09-07-69" geburtsort="Palakkad" todesdatum="" ehepartner="" mutter="9" vater="10" id="21" familyId=""/>
            <Mann vorname="Aaron" nachname="Casey" geburtsdatum="26-01-10" geburtsort="Tampa" todesdatum="" ehepartner="" mutter="9" vater="10" id="22" familyId=""/>
            <Mann vorname="Ian" nachname="Casey" geburtsdatum="08-01-44" geburtsort="Otricoli" todesdatum="" ehepartner="" mutter="9" vater="10" id="23" familyId=""/>


            <Frau vorname="Hilary" nachname="Lee" geburtsdatum="09-12-45" geburtsort="Pike Creek" todesdatum="" ehepartner="" mutter="11" vater="12" id="24" familyId=""/>
            <Mann vorname="Lucas" nachname="Lee" geburtsdatum="22-03-87" geburtsort="Shchyolkovo" todesdatum="" ehepartner="" mutter="11" vater="12" id="25" familyId=""/>
            <generation>
                <Frau vorname="Amela" nachname="Riddle" geburtsdatum="03-07-64" geburtsort="East Linton" todesdatum="" ehepartner="6" mutter="" vater="" id="5" familyId=""/>
                <Mann vorname="Allen" nachname="Lee" geburtsdatum="18-04-83" geburtsort="Doues" todesdatum="" ehepartner="5" mutter="1" vater="2" id="6" familyId=""/>

                <Frau vorname="Mara" nachname="Rutledge" geburtsdatum="13-07-65" geburtsort="Wood Buffalo" todesdatum="" ehepartner="8" mutter="" vater="" id="7" familyId=""/>
                <Mann vorname="Otto" nachname="Lee" geburtsdatum="08-06-04" geburtsort="Tucson" todesdatum="" ehepartner="7" mutter="1" vater="2" id="8" familyId=""/>

                <Frau vorname="Rebecca" nachname="Lee" geburtsdatum="12-02-85" geburtsort="Blue Mountains" todesdatum="" ehepartner="10" mutter="1" vater="2" id="9" familyId=""/>
                <Mann vorname="Dale" nachname="Casey" geburtsdatum="22-12-98" geburtsort="Tielen" todesdatum="" ehepartner="9" mutter="" vater="" id="10" familyId=""/>

                <Frau vorname="Jena" nachname="Fry" geburtsdatum="10-05-83" geburtsort="Rodez" todesdatum="" ehepartner="12" mutter="3" vater="4" id="11" familyId=""/>
                <Mann vorname="Martin" nachname="Lee" geburtsdatum="16-10-40" geburtsort="Meix-le-Tige" todesdatum="" ehepartner="11" mutter="1" vater="2" id="12" familyId=""/>
                <generation>
                    <Frau vorname="Martina" nachname="Kirk" geburtsdatum="02-02-95" geburtsort="Delft" todesdatum="" ehepartner="2" mutter="" vater="" id="1" familyId=""/>
                    <Mann vorname="Quinn" nachname="Lee" geburtsdatum="11-03-87" geburtsort="Itterbeek" todesdatum="" ehepartner="1" mutter="" vater="" id="2" familyId=""/>

                    <Frau vorname="Addison" nachname="Larson" geburtsdatum="18-08-51" geburtsort="Saint-Dizier" todesdatum="4" ehepartner="" mutter="" vater="" id="3" familyId=""/>
                    <Mann vorname="Guy" nachname="Fry" geburtsdatum="04-04-63" geburtsort="Merritt" todesdatum="" ehepartner="3" mutter="" vater="" id="4" familyId=""/>
                </generation>
            </generation>
        </generation>
    </generation>
</familie>