<?xml-stylesheet type="text/xsl" href="stammbaum2.xsl"?>
<!DOCTYPE stammbaum [
<!ELEMENT stammbaum (familie+)>
<!ELEMENT familie (generation)>
<!ELEMENT generation (Person | generation)*>
<!ELEMENT Person EMPTY>
<!ATTLIST  Person 
    vorname CDATA #REQUIRED
    nachname CDATA #REQUIRED
    geschlecht CDATA #REQUIRED
    geburtsdatum CDATA #REQUIRED
    geburtsort CDATA #REQUIRED
    todesdatum CDATA #IMPLIED
    ehepartner CDATA #IMPLIED
    mutter CDATA #IMPLIED
    vater CDATA #IMPLIED
    id CDATA #REQUIRED
    familyId CDATA #IMPLIED
>]>
<stammbaum>
    <familie>
        <generation>
            <Person vorname="Alexandra" nachname="Ewing" geschlecht="weiblich" geburtsdatum="15-01-36" geburtsort="Laken" todesdatum="" ehepartner="" mutter="16" vater="15" id="54" familyId=""/>
            <Person vorname="Brenden" nachname="Ewing" geschlecht="männlich" geburtsdatum="01-06-46" geburtsort="Enna" todesdatum="" ehepartner="" mutter="16" vater="15" id="78" familyId=""/>
            <generation>
                <Person vorname="Jasmine" nachname="Lee" geschlecht="weiblich" geburtsdatum="11-08-48" geburtsort="Bearberry" todesdatum="" ehepartner="" mutter="5" vater="6" id="13" familyId=""/>
                <Person vorname="Finn" nachname="Lee" geschlecht="männlich" geburtsdatum="29-12-16" geburtsort="Lacombe County" todesdatum="" ehepartner="" mutter="5" vater="6" id="14" familyId=""/>
                <Person vorname="Arthur" nachname="Ewing" geschlecht="männlich" geburtsdatum="19-07-58" geburtsort="Pereira" todesdatum="" ehepartner="16" mutter="" vater="" id="15" familyId=""/>
                <Person vorname="Kylee" nachname="Lee" geschlecht="weiblich" geburtsdatum="15-12-98" geburtsort="Acireale" todesdatum="" ehepartner="15" mutter="5" vater="6" id="16" familyId=""/>


                <Person vorname="Stacy" nachname="Lee" geschlecht="weiblich" geburtsdatum="26-09-41" geburtsort="Colobraro" todesdatum="" ehepartner="" mutter="7" vater="8" id="17" familyId=""/>
                <Person vorname="Hilda" nachname="Lee" geschlecht="weiblich" geburtsdatum="28-07-16" geburtsort="Lavoir" todesdatum="" ehepartner="" mutter="7" vater="8" id="18" familyId=""/>
                <Person vorname="Amos" nachname="Lee" geschlecht="männlich" geburtsdatum="06-03-44" geburtsort="Ninhue" todesdatum="" ehepartner="20" mutter="7" vater="8" id="19" familyId=""/>
                <Person vorname="Halla" nachname="Watkins" geschlecht="weiblich" geburtsdatum="21-12-17" geburtsort="Lille" todesdatum="" ehepartner="19" mutter="" vater="" id="20" familyId=""/>


                <Person vorname="Bert" nachname="Casey" geschlecht="männlich" geburtsdatum="09-07-69" geburtsort="Palakkad" todesdatum="" ehepartner="" mutter="9" vater="10" id="21" familyId=""/>
                <Person vorname="Aaron" nachname="Casey" geschlecht="männlich" geburtsdatum="26-01-10" geburtsort="Tampa" todesdatum="" ehepartner="" mutter="9" vater="10" id="22" familyId=""/>
                <Person vorname="Ian" nachname="Casey" geschlecht="männlich" geburtsdatum="08-01-44" geburtsort="Otricoli" todesdatum="" ehepartner="" mutter="9" vater="10" id="23" familyId=""/>


                <Person vorname="Hilary" nachname="Lee" geschlecht="weiblich" geburtsdatum="09-12-45" geburtsort="Pike Creek" todesdatum="" ehepartner="" mutter="11" vater="12" id="24" familyId=""/>
                <Person vorname="Lucas" nachname="Lee" geschlecht="männlich" geburtsdatum="22-03-87" geburtsort="Shchyolkovo" todesdatum="" ehepartner="" mutter="11" vater="12" id="25" familyId=""/>
                <generation>
                    <Person vorname="Amela" nachname="Riddle" geschlecht="weiblich" geburtsdatum="03-07-64" geburtsort="East Linton" todesdatum="" ehepartner="6" mutter="" vater="" id="5" familyId=""/>
                    <Person vorname="Allen" nachname="Lee" geschlecht="männlich" geburtsdatum="18-04-83" geburtsort="Doues" todesdatum="" ehepartner="5" mutter="1" vater="2" id="6" familyId=""/>

                    <Person vorname="Mara" nachname="Rutledge" geschlecht="weiblich" geburtsdatum="13-07-65" geburtsort="Wood Buffalo" todesdatum="" ehepartner="8" mutter="" vater="" id="7" familyId=""/>
                    <Person vorname="Otto" nachname="Lee" geschlecht="männlich" geburtsdatum="08-06-04" geburtsort="Tucson" todesdatum="" ehepartner="7" mutter="1" vater="2" id="8" familyId=""/>

                    <Person vorname="Rebecca" nachname="Lee" geschlecht="weiblich" geburtsdatum="12-02-85" geburtsort="Blue Mountains" todesdatum="" ehepartner="10" mutter="1" vater="2" id="9" familyId=""/>
                    <Person vorname="Dale" nachname="Casey" geschlecht="männlich" geburtsdatum="22-12-98" geburtsort="Tielen" todesdatum="" ehepartner="9" mutter="" vater="" id="10" familyId=""/>

                    <Person vorname="Jena" nachname="Fry" geschlecht="weiblich" geburtsdatum="10-05-83" geburtsort="Rodez" todesdatum="" ehepartner="12" mutter="3" vater="4" id="11" familyId=""/>
                    <Person vorname="Martin" nachname="Lee" geschlecht="männlich" geburtsdatum="16-10-40" geburtsort="Meix-le-Tige" todesdatum="" ehepartner="11" mutter="1" vater="2" id="12" familyId=""/>
                    <generation>
                        <Person vorname="Martina" nachname="Kirk" geschlecht="weiblich" geburtsdatum="02-02-95" geburtsort="Delft" todesdatum="" ehepartner="2" mutter="" vater="" id="1" familyId=""/>
                        <Person vorname="Quinn" nachname="Lee" geschlecht="männlich" geburtsdatum="11-03-87" geburtsort="Itterbeek" todesdatum="" ehepartner="1" mutter="" vater="" id="2" familyId=""/>

                        <Person vorname="Addison" nachname="Larson" geschlecht="weiblich" geburtsdatum="18-08-51" geburtsort="Saint-Dizier" todesdatum="" ehepartner="4" mutter="" vater="" id="3" familyId=""/>
                        <Person vorname="Guy" nachname="Fry" geschlecht="männlich" geburtsdatum="04-04-63" geburtsort="Merritt" todesdatum="" ehepartner="3" mutter="" vater="" id="4" familyId=""/>
                    </generation>
                </generation>
            </generation>
        </generation>
    </familie>
    <familie>
        <generation>
            <Person vorname="Arthur" nachname="Ewing" geschlecht="männlich" geburtsdatum="19-07-58" geburtsort="Pereira" todesdatum="" ehepartner="16" mutter="" vater="" id="100" familyId=""/>
            <Person vorname="Kylee" nachname="Lee" geschlecht="weiblich" geburtsdatum="15-12-98" geburtsort="Acireale" todesdatum="" ehepartner="15" mutter="5" vater="6" id="200" familyId=""/>
        </generation>
    </familie>
     <familie>
        <generation>
            <Person vorname="Arthur" nachname="Ewing" geschlecht="männlich" geburtsdatum="19-07-58" geburtsort="Pereira" todesdatum="" ehepartner="16" mutter="" vater="" id="300" familyId=""/>
            <Person vorname="Kylee" nachname="Lee" geschlecht="weiblich" geburtsdatum="15-12-98" geburtsort="Acireale" todesdatum="" ehepartner="15" mutter="5" vater="6" id="400" familyId=""/>
        </generation>
    </familie>
</stammbaum>